name: JUnit Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  greeting: hallo

jobs:
  password_please:
    runs-on: ubuntu-latest
    env:
      receiver: receiver
    steps:
      - name: Secret dialog
        run: echo $greeting $Dialog_Partner, das Passwort für $passwort ist ${{ secrets.PASSWORT_KEY }}!
        env:
          passwort: 'Account'

  build-test:
    strategy:
      matrix:
        java: [11, 17, 21]
    name: Build and Test with Maven on Java ${{ matrix.java }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Build and Test with Maven
        run: mvn -B clean verify
    
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/

  lint:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Checkstyle report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: target/checkstyle-result.xml
